#!/bin/sh
set -eu

usage() {
  cat <<'EOF'
Usage:
  collect-target-networkd.sh [--out-dir DIR] [--stdout] [--iface IFACE]

Collect the current Linux runtime network state and render Arch/systemd-networkd
configuration files for a custom DD image.

Defaults:
  --out-dir ./arch-dd-networkd

Notes:
  - This script does not change the running system.
  - It reads ip(8), /sys/class/net, and /etc/resolv.conf only.
  - Static target configs are matched by MACAddress, so they do not apply to a
    different server. A DHCP/IPv6-RA fallback file is also generated.
EOF
}

out_dir=./arch-dd-networkd
stdout=0
forced_iface=

while [ "$#" -gt 0 ]; do
  case "$1" in
    --out-dir)
      [ "$#" -ge 2 ] || { echo "--out-dir needs a value" >&2; exit 2; }
      out_dir=$2
      shift 2
      ;;
    --stdout)
      stdout=1
      shift
      ;;
    --iface)
      [ "$#" -ge 2 ] || { echo "--iface needs a value" >&2; exit 2; }
      forced_iface=$2
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

need_cmd() {
  command -v "$1" >/dev/null 2>&1 || {
    echo "Missing required command: $1" >&2
    exit 1
  }
}

need_cmd ip
need_cmd awk
need_cmd sed

clean_iface() {
  printf '%s\n' "$1" | sed 's/@.*//'
}

sanitize_name() {
  printf '%s\n' "$1" | sed 's/[^A-Za-z0-9_.-]/_/g'
}

append_unique_iface() {
  iface=$(clean_iface "$1")
  [ -n "$iface" ] || return 0
  [ "$iface" != lo ] || return 0
  [ -e "/sys/class/net/$iface/address" ] || return 0
  case " $ifaces " in
    *" $iface "*) ;;
    *) ifaces="$ifaces $iface" ;;
  esac
}

route_has_dev() {
  ver=$1
  dev=$2
  ip "-$ver" route show default 2>/dev/null |
    awk -v d="$dev" '
      {
        for (i = 1; i <= NF; i++) {
          if ($i == "dev" && (i + 1) <= NF && $(i + 1) == d) {
            found = 1
          }
        }
      }
      END { exit found ? 0 : 1 }
    '
}

route_gateway() {
  ver=$1
  dev=$2
  ip "-$ver" route show default 2>/dev/null |
    awk -v d="$dev" '
      {
        hasdev = 0
        gw = ""
        for (i = 1; i <= NF; i++) {
          if ($i == "dev" && (i + 1) <= NF && $(i + 1) == d) {
            hasdev = 1
          }
          if ($i == "via" && (i + 1) <= NF) {
            gw = $(i + 1)
          }
        }
        if (hasdev && gw != "") {
          print gw
          exit
        }
      }
    '
}

default_ifaces() {
  ip -4 route show default 2>/dev/null |
    awk '{for (i = 1; i <= NF; i++) if ($i == "dev" && (i + 1) <= NF) print $(i + 1)}'
  ip -6 route show default 2>/dev/null |
    awk '{for (i = 1; i <= NF; i++) if ($i == "dev" && (i + 1) <= NF) print $(i + 1)}'
}

fallback_iface() {
  ip -o link show up 2>/dev/null |
    awk -F': ' '$2 != "lo" {sub(/@.*/, "", $2); print $2; exit}'
}

dns_lines() {
  if [ -r /etc/resolv.conf ]; then
    awk '/^[[:space:]]*nameserver[[:space:]]+/ {print $2}' /etc/resolv.conf |
      awk '
        $0 ~ /^127\./ {next}
        $0 == "::1" {next}
        $0 == "0.0.0.0" {next}
        $0 == "::" {next}
        NF && !seen[$0]++ {print "DNS="$0}
      '
  fi
}

emit_fallback() {
  cat <<'EOF'
[Match]
Name=*

[Network]
DHCP=yes
IPv6AcceptRA=yes

[DHCPv4]
UseDNS=yes
UseRoutes=yes

[IPv6AcceptRA]
UseDNS=yes
UseGateway=yes
EOF
}

emit_target_network() {
  dev=$1
  mac=$(cat "/sys/class/net/$dev/address")
  gw4=$(route_gateway 4 "$dev" || true)
  gw6=$(route_gateway 6 "$dev" || true)
  has4=0
  has6=0
  route_has_dev 4 "$dev" && has4=1 || true
  route_has_dev 6 "$dev" && has6=1 || true

  cat <<EOF
# Generated by collect-target-networkd.sh
# Source interface: $dev

[Match]
MACAddress=$mac

[Network]
IPv6AcceptRA=yes
EOF

  dns=$(dns_lines || true)
  if [ -n "$dns" ]; then
    printf '%s\n' "$dns"
  else
    echo "DNS=1.1.1.1"
    echo "DNS=2606:4700:4700::1111"
  fi

  ip -o -4 addr show dev "$dev" scope global 2>/dev/null |
    awk '{print "Address="$4}'
  ip -o -6 addr show dev "$dev" scope global 2>/dev/null |
    awk '$0 !~ / temporary / && $0 !~ / tentative / && $0 !~ / deprecated / {print "Address="$4}'

  cat <<'EOF'

[IPv6AcceptRA]
UseDNS=yes
UseGateway=yes
EOF

  if [ "$has4" = 1 ]; then
    cat <<'EOF'

[Route]
Destination=0.0.0.0/0
EOF
    if [ -n "$gw4" ]; then
      echo "Gateway=$gw4"
      echo "GatewayOnLink=yes"
    fi
  fi

  if [ "$has6" = 1 ]; then
    cat <<'EOF'

[Route]
Destination=::/0
EOF
    if [ -n "$gw6" ]; then
      echo "Gateway=$gw6"
      echo "GatewayOnLink=yes"
    fi
  fi
}

ifaces=
if [ -n "$forced_iface" ]; then
  append_unique_iface "$forced_iface"
else
  default_ifaces | while IFS= read -r dev; do
    [ -n "$dev" ] && printf '%s\n' "$(clean_iface "$dev")"
  done >"${TMPDIR:-/tmp}/collect-networkd-ifaces.$$"
  while IFS= read -r dev; do
    append_unique_iface "$dev"
  done <"${TMPDIR:-/tmp}/collect-networkd-ifaces.$$"
  rm -f "${TMPDIR:-/tmp}/collect-networkd-ifaces.$$"
  if [ -z "$ifaces" ]; then
    append_unique_iface "$(fallback_iface || true)"
  fi
fi

if [ -z "$ifaces" ]; then
  echo "Could not find a usable non-loopback interface" >&2
  exit 1
fi

if [ "$stdout" != 1 ]; then
  mkdir -p "$out_dir"
fi

for dev in $ifaces; do
  name=$(sanitize_name "$dev")
  file="10-target-${name}.network"
  if [ "$stdout" = 1 ]; then
    echo "### $file"
    emit_target_network "$dev"
    echo
  else
    emit_target_network "$dev" >"$out_dir/$file"
    chmod 0644 "$out_dir/$file"
    echo "wrote $out_dir/$file" >&2
  fi
done

if [ "$stdout" = 1 ]; then
  echo "### 90-dhcp-fallback.network"
  emit_fallback
else
  emit_fallback >"$out_dir/90-dhcp-fallback.network"
  chmod 0644 "$out_dir/90-dhcp-fallback.network"
  echo "wrote $out_dir/90-dhcp-fallback.network" >&2
fi
